[versions]
paper = "1.18.2-R0.1-SNAPSHOT"
papi = "2.12.3"

okaeri = "5.0.13"
bstats = "3.2.1"
folialib = "0.5.2"
commons = "0.3.0"
lamp = "4.0.0-rc.18"
actions = "0.2.0"

shadow = "9.6.1"
lombok = "9.5.0"
pluginyml = "0.9.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
papi = { module = "me.clip:placeholderapi", version.ref = "papi" }

okaeri = { module = "eu.okaeri:okaeri-configs-yaml-bukkit", version.ref = "okaeri" }
okaeri-serdes = { module = "eu.okaeri:okaeri-configs-serdes-bukkit", version.ref = "okaeri" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
folialib = { module = "com.tcoded:FoliaLib", version.ref = "folialib" }
commons = { module = "top.vulpine:commons", version.ref = "commons" }
actions = { module = "top.vulpine:actions", version.ref = "actions" }
lamp-common = { module = "io.github.revxrsal:lamp.common", version.ref = "lamp" }
lamp-bukkit = { module = "io.github.revxrsal:lamp.bukkit", version.ref = "lamp" }

[plugins ]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
pluginyml = { id = "de.eldoria.plugin-yml.bukkit", version.ref = "pluginyml" }