[versions]
paper = "1.18.2-R0.1-SNAPSHOT"
papi = "2.11.6"

okaeri = "5.0.13"
bstats = "3.2.1"
folialib = "0.5.1"
commons = "0.1.0"

shadow = "9.3.0"
lombok = "9.2.0"

[libraries]
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }
papi = { module = "me.clip:placeholderapi", version.ref = "papi" }

okaeri = { module = "eu.okaeri:okaeri-configs-yaml-bukkit", version.ref = "okaeri" }
okaeri-serdes = { module = "eu.okaeri:okaeri-configs-serdes-bukkit", version.ref = "okaeri" }
bstats = { module = "org.bstats:bstats-bukkit", version.ref = "bstats" }
folialib = { module = "com.tcoded:FoliaLib", version.ref = "folialib" }
commons = { module = "top.vulpine:commons", version.ref = "commons" }

[plugins ]
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }
